name: DataForge CI

on:
    push:
        branches:
            - main

jobs: 
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.8'

            - name: Install dbt
              run: pip install dbt-core dbt-snowflake

            - name: Create dbt profile
              run: |
                mkdir -p ~/.dbt
                cat <<EOF > ~/.dbt/profiles.yml
                dbt_dataforge:
                    target: dev
                    outputs:
                        dev:
                            type: snowflake
                            account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
                            user: ${{ secrets.SNOWFLAKE_USER }}
                            password: ${{ secrets.SNOWFLAKE_PASSWORD }}
                            role: ${{ secrets.SNOWFLAKE_ROLE }}
                            database: ${{ secrets.SNOWFLAKE_DATABASE }}
                            warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
                            schema: public
                            threads: 1
                EOF   

            - name: Debug secrets
              run: echo "Account is ${{ secrets.SNOWFLAKE_ACCOUNT }}"
              

            - name: Run dbt
              run: |
                cd dbt_dataforge
                dbt run

